### PR TITLE
Create a component for header

### LINKED ISSUE #434: Make headers uniform format
Make a component that will be used to render headers.

### PR DESCRIPTION
**Pull request by jerrylee17**
Resolves #434

To use the header, import it to your file: 
```js
import Header from
  '../../Components/Header/Header.js';
```

Create props
```js
const headerProps = {
    title: 'SCE Printing System'
};
```

Create the component
```js
<Header {...headerProps} />
```

The result is a header that looks like this:

### CODE REVIEW

**Comment by evanugarte** [comment]
@jerrylee17 can you add some screenshots on what will change and rebase?

**Comment by jerrylee17** [comment]
> Few things:
> 
> 1. Please add test cases for this component
> 2. Where else would you like to use this?
> 3. Add labels to this pr, the milestone and assign yourself

1. Ok doing this now
2. Should I just add this to wherever I see fit? I think all pages should have it so the SCE website has a uniform format. 
3. Done

**Comment by evanugarte** [comment]
One of the things I want to improve is our UI. While this component is helpful, this black font on grey title is not it for styling in my opinion.

**Comment by evanugarte** [comment]
@jerrylee17 Lets work to improve the UI of 2D printing on it's own instead

**Comment by evanugarte** [comment]
I think the intention here is good, but we should focus on improving the UI of 2D and 3D pages individually. After we can move onto working on this.

**Pull request closed without merging**
