### PR TITLE
Add Docker to Containerize Services

### LINKED ISSUE #356: Containerize SCE Website
Using [Docker](https://www.docker.com/why-docker), let's put the frontend, server and RPC code into containers. This will allow for scalability and better follow industry standards.

### PR DESCRIPTION
**Pull request by evanugarte**
Resolves #356

## How to Test this PR
**You have to have linux!**
1. Install docker using [this guide](https://docs.docker.com/engine/install/ubuntu/)
1. Install docker-compose [like this](https://docs.docker.com/compose/install/)
1. In Core-v4 directory, type `sudo docker-compose up`. This will create 3 containers for mongdb, our backend and our frontend.
1. Run `mongo`, and insert the credentials with these two commands:
```
> use sce_core
> db.User.insert({ "emailVerified" : true, "emailOptIn" : true, "accessLevel" : 3, "pagesPrinted" : 0, "password" : "$2a$10$FuaDGcGnictCrve.mLR2Ve5NzhU5JBwBghse5RBNB/kC/zGZQEJmu", "firstName" : "first test", "lastName" : "used asycn await", "email" : "a@a.com", "major" : "", "joinDate" : ISODate("2020-03-18T02:43:38.573Z"), "lastLogin" : ISODate("2020-04-13T05:12:32.605Z"), "membershipValidUntil" : ISODate("2020-09-01T02:43:38.574Z"), "__v" : 0 })
```
5. Use the website ensuring things work as expected. The credentials to sign in are `a@a.com`, `Passw0rd!`

### CODE REVIEW

**Comment by ThaiQ** [comment]
Evan said, "you are a dummy"
image

**Comment by hsorathia** [comment]
not sure why, but it's not really working for me

**Comment by evanugarte** [comment]
@hsorathia you arent supposed to run any npm commands after `docker-compose up`. the command runs everything for you

**Comment by evanugarte** [comment]
Closing this until i finish my weekend missions

**Pull request closed without merging**
