### PR TITLE
make each pr build step its own job

### PR DESCRIPTION
**Pull request by akshtshrma24**

### CODE REVIEW

**Comment by evanugarte** [comment]
55 second pr builds!!!

**Review by crowbardispensingcore — APPROVED** [review]

**Comment by danknessdra** [comment]
this is one of the best PR i ever seen in my life i want to approve this and kiss it

**Review by danknessdra — APPROVED** [review]

**Review by Luceium — APPROVED** [review]
Lgtm

**Review by praveenksamy148 — APPROVED** [review]
big pr W

**Pull request merged**
