### PR TITLE
Resolved #194, Fixing global css pointers in Overview

### LINKED ISSUE #194: Overview input css destroyed my printing page
change src/Pages/Overview/Overview.css to use classes/id's instead of changing all the inputs.  The issue can be found in [this file](https://github.com/SCE-Development/Core-v4/blob/c8aa745cc4702201f1d7e8bb9fce818e36f04ce8/src/Pages/Overview/Overview.css#L65)

```css
input, select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0px;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-size: 16px;
  initial-letter-align: left
}
```

### PR DESCRIPTION
**Pull request by ThaiQ**
Adding className field to html frontend  which then referring the component by css

Resolved [#194](https://github.com/SCE-Development/Core-v4/issues/194)

### CODE REVIEW

**Comment by evanugarte** [comment]
Also add `Resolves #194`  to your PR description so when we merge this the issue is closed.

**Comment by evanugarte** [comment]
No. Just type "Resolves #194"
image

**Comment by ThaiQ** [comment]
got it @evanugarte

**Comment by evanugarte** [comment]
Also can you squash your commits and rename them? Rename this PR too.

**Pull request merged**
