### PR TITLE
minor ui fixes: footer button color, project name spacing

### PR DESCRIPTION
**Pull request by nayasinghania**
fixed youtube footer icon to match fill color with discord icon and github icon by changing the value for fill in the <g> tag within the <svg> tag for youtube in src/components/Footer.js.

Before:
Screenshot 2024-09-26 143115

After: 
Screenshot 2024-09-26 143130

### CODE REVIEW

**Review by pnavab — APPROVED** [review]
cool

**Review by danknessdra — APPROVED** [review]
LGTM, Thanks for the taking the initiative!

**Comment by nayasinghania** [comment]
second commit: added spacing so spacing above and below project names is equivalent

Before:
Screenshot 2024-09-26 145337


After:
Screenshot 2024-09-26 145324

**Comment by danknessdra** [comment]
still lgtm for me

**Review by joshua-demo — APPROVED** [review]
lgtm

**Comment by evanugarte** [comment]
cool

**Comment by nayasinghania** [comment]
i think one of yall may have to merge this for me, the pr is approved but seems like i am unable to merge it
image

**Pull request merged**
