### PR TITLE
F2021 Blasts

### PR DESCRIPTION
**Pull request by nanarboursal**

### CODE REVIEW

**Comment by au01gh** [comment]
SCE_General_Meeting

**Comment by au01gh** [comment]
Cisco

**Comment by au01gh** [comment]
scehacks_2021

**Comment by Christopher-Tom** [comment]
sceGameNightFlyerF21

**Comment by au01gh** [comment]
Resume Workshop

**Comment by au01gh** [comment]
scehacks 2021

**Comment by au01gh** [comment]
scehacks_2021_2

**Comment by au01gh** [comment]
Gen_Meeting

**Comment by au01gh** [comment]
QA

**Pull request closed without merging**
