### PR TITLE
Adding Dark Mode to Admin Navbar

### LINKED ISSUE #648: Add Darkmode Toggler to Admin Navbar
Darkmode can only be toggled on the user navbar. Adding it to the admin navbar should enhance UX

### PR DESCRIPTION
**Pull request by fmasood23**
Resolves #648

### CODE REVIEW

**Review by law-nguyen — APPROVED** [review]
it works for me

**Review by law-nguyen — CHANGES_REQUESTED** [review]
mmmm  just kidding looks like you gotta fix some lint

**Review by hsorathia — APPROVED** [review]
lgtm

**Review by law-nguyen — APPROVED** [review]
WOOO

**Review by jerrylee17 — APPROVED** [review]

**Review by aashrav — APPROVED** [review]
Looks good

**Review by IsitaB — APPROVED** [review]

**Pull request merged**
