### PR TITLE
Add token verification to LED Sign 

### LINKED ISSUE #1015: Add token verification to LED sign API
basically #442 but in [`api/peripheral_api/routes/LedSign.js`](https://github.com/SCE-Development/Core-v4/blob/370ba6774cb7ebe8a732d455304b807609ef91bf/api/peripheral_api/routes/LedSign.js). we don't check tokens atm meaning anyone who knows `curl` or Postman can write whatever they want to our LED sign.

### PR DESCRIPTION
**Pull request by neelp03**
## Resolves #1015 
- Added token verification to LED Sign for security
- Created SQS API handler mocks which will be used later for other peripheral tests

### CODE REVIEW

**Comment by allen-tran** [comment]
top 5 contributor incoming 🚀

**Review by evanugarte — APPROVED** [review]
Lollygaggers, tomfoolerers, jokers, hoaxers, tricksters, jokesmiths, humorists, and other ridiculous students trying to update the sign without being an admin after this pr gets merged:

image

**Comment by neelp03** [comment]
# DON'T MERGE YET!

**Comment by andrewtedi** [comment]
📈📈📈

**Review by andrewtedi — APPROVED** [review]

**Pull request merged**
