### PR TITLE
Remove duplicate PrintLog.js file

### PR DESCRIPTION
**Pull request by allen-tran**
This file is a duplicate of [api/logging_api/models/PrintLog.js](https://github.com/SCE-Development/Core-v4/blob/932cad6f7fa1ec9e01d91b2cff54455ae930fa24/api/logging_api/models/PrintLog.js), no need for it.

### CODE REVIEW

**Comment by evanugarte** [comment]
very motivational!!!


image

**Comment by allen-tran** [comment]
pat

**Comment by andrewtedi** [comment]
Looking cool Allen!

**Review by evanugarte — APPROVED** [review]
Looks good, let others review before merging

**Review by andrewtedi — APPROVED** [review]

**Review by imdominicreed — APPROVED** [review]
wow very nice and intense coder!!!!!

**Review by crowbardispensingcore — APPROVED** [review]

**Comment by crowbardispensingcore** [comment]
image

**Pull request merged**
