### PR TITLE
 Refactored Routing + Navbar Rendering

### PR DESCRIPTION
**Pull request by evanugarte**
We now check for the user's auth status in the highest component and use a
custom PrivateRoute component for securing routes. We also now use array.map in a seperate file, Routing.js to render the routes

Each component in Routing.js is wrapped by the NavbarWrapper
component. NavbarWrapper renders the correct component based on the
route and user's account priviledge level.

we now have collapsable navbars!
image

### CODE REVIEW

**Comment by ThaiQ** [comment]
'Snack and Food' is repeated, the 2nd 'Snack and Food' should be The Team since it routes to '/Team'
image

Dashboard is messed up, cannot click on its nav bar
image

Dont need this since 'Home' go back home
image

**Comment by ThaiQ** [comment]
Please keep it blue, grey just not fit with a lot of our design
image

Does the logout button suppose to be like that?
image

Drop downs are hidden
image

**Comment by ThaiQ** [comment]
they are all shifted left now. They should shift right as the home page nav
image

**Comment by evanugarte** [comment]
@ThaiQ fixed. please also add review comments from now on with the green button on the right side:
image

**Comment by ThaiQ** [comment]
I know i just dont :))

**Pull request merged**
