### PR TITLE
Update AdminDashboard UI

### PR DESCRIPTION
**Pull request by davidtanline**
Screen Shot 2022-07-04 at 3 59 50 PM
Screen Shot 2022-07-04 at 4 06 18 PM

### CODE REVIEW

**Review by neelp03 — CHANGES_REQUESTED** [review]
I think you should change the background to a dark color so the theme is consistent with all of our other pages but overall looks good.

**Review by neelp03 — CHANGES_REQUESTED** [review]
Nice, it looks better with the dark bg color. You should also make the dashboard items smaller (see attached image). You also have some unused imports which have to be removed. When I click the dashboard items, it doesn't actually send me to the corresponding page, what it did was change the url only. The url changes but its not actually rendering that page (or loading that page, equivalent to entering a url and clicking enter). Lmk if that makes sense or not.

image

**Comment by davidtanline** [comment]
Screen Shot 2022-07-06 at 8 01 02 PM

Updated UI, made items smaller

**Review by ShaivPandya — APPROVED** [review]

**Review by neelp03 — APPROVED** [review]
I'm with it.

**Pull request merged**
