### PR TITLE
Rename Token Mocking Functions

### LINKED ISSUE #1056: Rename Token Mocking Functions
With #1048 and #1049 being merged, a new function was added to mock SQS [logic](https://github.com/SCE-Development/Core-v4/blob/5be69aeccc710a160473ddd11df8340af9847bb8/test/util/mocks/SceSqsApiHandler.js#L19). We should do this for the [Token Functions](https://github.com/SCE-Development/Core-v4/blob/5be69aeccc710a160473ddd11df8340af9847bb8/test/util/mocks/TokenValidFunctions.js#L13), to make the function names less vague.

### PR DESCRIPTION
**Pull request by sohumtiwary**
resolves #1056

### CODE REVIEW

**Review by neelp03 — CHANGES_REQUESTED** [review]
Good work renaming the token functions, but there are some random changes in the package.json and package-lock.json files.

**Comment by evanugarte** [comment]
this reminds me of @nanarboursal's #185

**Review by neelp03 — APPROVED** [review]
Looks good to me!

**Review by andrewtedi — APPROVED** [review]

**Review by allen-tran — APPROVED** [review]
https://user-images.githubusercontent.com/63386979/160730437-c6fdd3ae-12cf-4017-b395-2bb3404a674d.MOV

**Pull request merged**
