### PR TITLE
Closes docker ports in production

### LINKED ISSUE #927: Close Docker Ports in Core-v4 Prod
The only ports that should be open when running in prod are 443 and 80. All other mention of ports in
[docker-compose.yml](https://github.com/SCE-Development/Core-v4/blob/71fd33cd7614b755b623bac652fbd248477a000e/docker-compose.yml) should be removed! As it stands now, anyone on the internet can connect to our MongoDB and read data.

docker.compose.yml file, remove the lines with ports

### PR DESCRIPTION
**Pull request by allen-tran**
### What does this do?
- [X] removes all ports except for 80 and 443 from yml file
- [X] prevents exposure of database in production by closing ports

## Comment
i'm not sure if this is gonna wreck production; i'm unfamiliar with deployment and all that jazz just lmk

### CODE REVIEW

**Comment by evanugarte** [comment]
Did you test this?

1. grab your ip address with `ifconfig`, its probably `192.168.68.x`
2. run sce with docker on said computer. might need to comment out [docker-compose.yml:73-74](https://github.com/SCE-Development/Core-v4/blob/ad50d690e35e8233ed243f99c7858074339023b0/docker-compose.yml#L73) since we haven't fixed #925 
3. access the sce website by visiting `192.168.68.x` from a different device
4. make sure you can login as admin, make some events and view them all from the different device

**Comment by allen-tran** [comment]
> Did you test this?
> 
> 1. grab your ip address with `ifconfig`, its probably `192.168.68.x`
> 2. run sce with docker on said computer. might need to comment out [docker-compose.yml:73-74](https://github.com/SCE-Development/Core-v4/blob/ad50d690e35e8233ed243f99c7858074339023b0/docker-compose.yml#L73) since we haven't fixed [Remove Assumption about Prod Environment for Docker Build #925](https://github.com/SCE-Development/Core-v4/issues/925)
> 3. access the sce website by visiting `192.168.68.x` from a different device
> 4. make sure you can login as admin, make some events and view them all from the different device

I'm getting blocked by step 3. I ran `docker-compose up` in the directory but when i try to access the ip from a diff device it does not work.

**Comment by allen-tran** [comment]
> > Did you test this?
> > 
> > 1. grab your ip address with `ifconfig`, its probably `192.168.68.x`
> > 2. run sce with docker on said computer. might need to comment out [docker-compose.yml:73-74](https://github.com/SCE-Development/Core-v4/blob/ad50d690e35e8233ed243f99c7858074339023b0/docker-compose.yml#L73) since we haven't fixed [Remove Assumption about Prod Environment for Docker Build #925](https://github.com/SCE-Development/Core-v4/issues/925)
> > 3. access the sce website by visiting `192.168.68.x` from a different device
> > 4. make sure you can login as admin, make some events and view them all from the different device
> 
> I'm getting blocked by step 3. I ran `docker-compose up` in the directory but when i try to access the ip from a diff device it does not work.
2022-01-29 at 8 27 19 PM
not sure if this even shows anything but here is the output after running docker file

**Comment by evanugarte** [comment]
did you do step 2?

**Comment by evanugarte** [comment]
sorry, also comment out [`nginx.conf:38-39`](https://github.com/SCE-Development/Core-v4/blob/ad50d690e35e8233ed243f99c7858074339023b0/nginx.conf#L38) too

**Comment by allen-tran** [comment]
> did you do step 2?

My bad i switched back to dev and forgot to do that. Nonetheless it still hasnt worked.

PS i dont need to have the sever and stuff running right?

**Comment by evanugarte** [comment]
> > did you do step 2?
> 
> My bad i switched back to dev and forgot to do that. Nonetheless it still hasnt worked.
> 
> PS i dont need to have the sever and stuff running right?

you do, lmk if that additional comment about nginx.conf helped

**Review by evanugarte — APPROVED** [review]
Verified this and it works

**Review by andrewtedi — APPROVED** [review]

**Pull request merged**
