### PR TITLE
Husky

### PR DESCRIPTION
**Pull request by RTX-Banana**
Set up Husky

### CODE REVIEW

**Comment by charlotte-zhuang** [comment]
What's the expected result? It doesn't seem to do anything when I make a push.

**Comment by RTX-Banana** [comment]
its supposed to auto run eslint when u git push

**Review by charlotte-zhuang — APPROVED** [review]
Note, you need to make the script executable.

Mac/Linux
`chmod +x .husky/pre-push`

I think it's questionable whether this improves our workflow. It might be annoying for commits that aren't ready to be reviewed.

The script executes on the current branch whenever you do a push. So if you want to perform an action on another branch, you can still be blocked. For example `git push origin --delete mybranch`.

**Review by aashrav — APPROVED** [review]
Looks good

If you do not want to run precheck you can always add `--no-verify` at the end of your command

**Comment by IsitaB** [comment]
^^ we'll be fine as long as we add it to the FAQ

consider adding the `chmod +x` part to our `setup.py`

**Comment by charlotte-zhuang** [comment]
@RTX-Banana I think you can merge this PR.

**Pull request closed without merging**
