### PR TITLE
added path of /spark to point to https://spark-scesjsu.webflow.io/

### PR DESCRIPTION
**Pull request by ajha7**
### How to test
- [x] make sure you have docker installed
- [x] change nginx.conf to be something like below:
```
patch -p1 <<EOF
diff --git a/nginx.conf b/nginx.conf
index cc66bdf..35c6e82 100644
--- a/nginx.conf
+++ b/nginx.conf
@@ -20,25 +20,20 @@ http {
         server sce-peripheral-api:8081;
     }
 
-    server {
-        #re-routing http to https server
-        listen 80 default_server;
-        listen [::]:80 default_server;
-        server_name _;
-        return 301 https://$host$request_uri;
-    }
+    # server {
+    #     #re-routing http to https server
+    #     listen 80 default_server;
+    #     listen [::]:80 default_server;
+    #     server_name _;
+    #     return 301 https://$host$request_uri;
+    # }
 
     # actual nginx server
     server {
 
         #443(https)
-        listen 443 ssl;
-
-        # ssl certificate
-        ssl_certificate sce_engr_sjsu_edu.cer;
-        ssl_certificate_key sce.key;
-        # TLS protocol (remember to update to the newest protocols for best security)
-        ssl_protocols TLSv1.3;
+        listen 80 default_server;
+        server_name _;
 
         #Load balancer
         location /api {
@@ -49,6 +44,9 @@ http {
         }
         location /peripheralapi {
             proxy_pass http://sce-peripheral-api;
+        }
+        location /spark {
+            proxy_pass https://spark-scesjsu.webflow.io/;
         }
         location / {
             proxy_pass http://webserver;
EOF
```
- [x] run the website with docker-compose up --build
- [x] ensure the cool spark website pops up when you go to http://localhost/spark
image

### CODE REVIEW

**Comment by evanugarte** [comment]
do we have an idea on what the ui will be?

if its a link on the navbar u can just do

```jsx
<Navlink href="https://spark-scesjsu.webflow.io/">
  SJSU Spark
</Navlink>
```

**Comment by ThaiQ** [comment]
Hey @ajha7, saw what you are doing - and yes it works but its not exactly what we want.

We want to be able to access/see the `https://spark-scesjsu.webflow.io` website through `https://sce.engr.sjsu.edu/spark` under our `.edu` domain.

What you are essentially doing is redirect users under `https://sce.engr.sjsu.edu/spark` to `https://spark-scesjsu.webflow.io` - but they still see webflow domain and we want to hide that.

The right direction is to config the Nginx Load Balancer in [nginx.conf - file](https://github.com/SCE-Development/Core-v4/blob/dev/nginx.conf). This way Nginx will handle domain proxy to our destination.

Something like this
```
       #Load balancer
        location /spark {
            proxy_pass https://spark-scesjsu.webflow.io;
        }
```
You will need docker-compose to run the entire projects to properly test this.

Message me in discord if you can't get this working.|

**Review by ThaiQ — CHANGES_REQUESTED** [review]
View comments at:

https://github.com/SCE-Development/Core-v4/pull/999#issuecomment-1054938503

**Comment by ThaiQ** [comment]
clarification: the only file we should change is the `nginx.conf` - hopefully as long as nothing changes since then

**Review by evanugarte — APPROVED** [review]
Tested this earlier and it works

**Review by ThaiQ — APPROVED** [review]
Tested on window host machine through docker-compose. Work!

However, need to edit links to `/spark/,,,` endpoint on webflow:
image

If you click on the links it will lead to 404error because webflow links doesn't follow `/spark/` endpoints.

**Review by andrewtedi — APPROVED** [review]

**Comment by allen-tran** [comment]
https://www.youtube.com/watch?v=5lanSif9wl8

**Pull request merged**
