### PR TITLE
Fixing callback url for email verification

### PR DESCRIPTION
**Pull request by ThaiQ**
To test:
- [x] Create a new account
- [x] verify email
- [x] login

### CODE REVIEW

**Comment by hsorathia** [comment]
it worked once, but then when i tried it with another email i never received the verification email

**Review by hsorathia — APPROVED** [review]

**Comment by hsorathia** [comment]
> it worked once, but then when i tried it with another email i never received the verification email
> edit: nvm i think that email was just wrong because it worked with another email :)

however one thing that i noticed was that when i click the verify link, although i'm not in a production environment the verify link redirects to our actual website
image

where the email doesn't exist. but, the link works if i append the the `/verify...` portion of the link to the end of my localhost link 
image

**Review by hsorathia — APPROVED** [review]

**Review by hsorathia — CHANGES_REQUESTED** [review]
see me comment

**Review by hsorathia — APPROVED** [review]
ignore my previous comments aaaaaaaaaaaa

**Review by law-nguyen — APPROVED** [review]
abcdefghijklmnopqrstuvwxyz

**Pull request merged**
