### PR TITLE
Dark mode switcher

### PR DESCRIPTION
**Pull request by Luceium**
Changes the toggle from a switch to a clickable icon.
When clicked the icons rotate clockwise about an origin located directly at the top of the screen.
The rotation implementation adds a state attribute to the functional component DarkMode.
image
image
image

### CODE REVIEW

**Comment by danknessdra** [comment]
npm run lint to check to resolve github checks if u didnt do it already 8)

**Comment by danknessdra** [comment]
also i would recommend to remove json file changes

**Comment by Luceium** [comment]
Thanks for letting me know about npm run lint! Also, I've removed the dependency changes.

**Review by neelp03 — APPROVED** [review]
Have merge conflicts due to new commits in dev, everything else lgtm

**Comment by Luceium** [comment]
Everything has been updated according to comments. @akshtshrma24 would you mind approving or leaving additional comments.

**Review by akshtshrma24 — APPROVED** [review]

**Pull request merged**
