### PR TITLE
Annabel/profile

### PR DESCRIPTION
**Pull request by Annabel1054**
Added a home button to navbar!

### CODE REVIEW

**Comment by ThaiQ** [comment]
@Annabel1054 update your branch is out of date! **Create a new branch from dev!** 
This branch has contents we do not want to merge 
```
git checkout dev
git pull origin dev
git checkout -b [your new branch name]
git checkout [your new branch name]
```

**Comment by evanugarte** [comment]
@ThaiQ But what if she has stuff on this branch that she wants to merge? We can update it as is.

**Comment by ThaiQ** [comment]
@evanugarte sure but I know this branch is the old branch we created before winter-break. We had too much changes since for me to be confident about rebasing. It is definitely a solution tho.

**Comment by ThaiQ** [comment]
@Annabel1054 In description write: Resolves #272

**Pull request closed without merging**
