### PR TITLE
Add user authentication to Printing and LED Sign APIs

### LINKED ISSUE #910: Add user authentication to Printing and LED Sign APIs
With #907 and #908 set to be merged soon, we need to make sure only authenticated members and officers be able to access the aforementioned APIs.

### How to do this
We need to be able to access [`api/main_endpoints/util/token-functions.js`](https://github.com/SCE-Development/Core-v4/blob/dev/api/main_endpoints/util/token-functions.js) from the logging directory. We can do this by moving the file to the [api/util](https://github.com/SCE-Development/Core-v4/tree/dev/api/util) directory and importing it from there.

Keep in mind that wherever these functions are used their import paths need to match the updated location!

### PR DESCRIPTION
**Pull request by allen-tran**
Resolves #910 

imageedit_2_9462952823

### CODE REVIEW

**Review by evanugarte — CHANGES_REQUESTED** [review]
Almost done!!

1. Merge `dev` into ur branch
2. ensure you change the include paths in the below files:
image
3. ensure tests pass with:
```
npm run api-test
```

**Review by evanugarte — CHANGES_REQUESTED** [review]
Fix failing build + merge conflict and we should b good to go

**Comment by allen-tran** [comment]
> Fix failing build + merge conflict and we should b good to go

Addressed.

**Review by evanugarte — APPROVED** [review]
This works i ran it locally and was able to sign in/out
image

**Review by imdominicreed — APPROVED** [review]
very nice code

**Comment by imdominicreed** [comment]
did mark zucc make this change?

**Pull request merged**
